load("//python:py_library.bzl", "py_library")
load("//tests/support:support.bzl", "NOT_WINDOWS")
load("//tests/support/pytest_test:pytest_test.bzl", "pytest_test")

py_library(
    name = "conftest",
    testonly = True,
    srcs = ["conftest.py"],
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":release_test_helper",
        "//dev/release:release_lib",
        "@pypi//pytest_mock",
    ],
)

py_library(
    name = "release_test_helper",
    testonly = True,
    srcs = ["release_test_helper.py"],
    data = ["//.github/ISSUE_TEMPLATE:release_tracking_template.md"],
    target_compatible_with = NOT_WINDOWS,
    deps = [
        "//dev/release:mock_gh",
        "//dev/release:release_lib",
        "//python/runfiles",
        "@pypi//pytest",
    ],
)

pytest_test(
    name = "add_backports_test",
    srcs = ["add_backports_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "changelog_news_test",
    srcs = ["changelog_news_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "complete_prepare_test",
    srcs = ["complete_prepare_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "complete_sync_changelog_test",
    srcs = ["complete_sync_changelog_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "sync_changelog_test",
    srcs = ["sync_changelog_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "create_release_branch_test",
    srcs = ["create_release_branch_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "create_release_issue_test",
    srcs = ["create_release_issue_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "git_test",
    srcs = ["git_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "on_pr_merged_test",
    srcs = ["on_pr_merged_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "promote_test",
    srcs = ["promote_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "release_issue_test",
    srcs = ["release_issue_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "release_test",
    srcs = ["release_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "backport_create_releases_test",
    srcs = ["backport_create_releases_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "prepare_test",
    srcs = ["prepare_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "gh_test",
    srcs = ["gh_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "backport_prepare_test",
    srcs = ["backport_prepare_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "process_backports_test",
    srcs = ["process_backports_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "create_rc_test",
    srcs = ["create_rc_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "process_news_test",
    srcs = ["process_news_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)

pytest_test(
    name = "utils_test",
    srcs = ["utils_test.py"],
    python_version = "3.14",
    target_compatible_with = NOT_WINDOWS,
    deps = [
        ":conftest",
        ":release_test_helper",
        "//dev/release:release_lib",
    ],
)
